version: '3.7'
services:
  deftbin-frontend:
    build: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app:rw
  deftbin-backend:
    build: backend
    ports:
      - 3001:3001
    volumes:
      - ./backend:/usr/src/app:rw

volumes:
  deftbin:
    external: true
